### ISSUE TITLE
Linker errors on Mac

### ISSUE THREAD

**Issue by thomasjm** [jakubfijalkowski/hsass#4]
I'm trying to build `hsass` as part of a cross-platform app. It works great on Linux, but on Mac I'm getting some linker errors:

```
    lookupSymbol failed in relocateSection (RELOC_GOT)
    /Users/tom/.stack/snapshots/x86_64-osx/lts-7.14/8.0.1/lib/x86_64-osx-ghc-8.0.1/hlibsass-0.1.5.0-A2JAkaXM35zEGvz8eJSuVp/libsass.a: unknown symbol `___dso_handle'
    ghc: Could not on-demand load symbol '__ZN4Sass10Expression11set_delayedEb'

    GHC runtime linker: fatal error: I found a duplicate definition for symbol
       __ZN4Sass10Expression11set_delayedEb
    whilst processing object file
       /Users/tom/.stack/snapshots/x86_64-osx/lts-7.14/8.0.1/lib/x86_64-osx-ghc-8.0.1/hlibsass-0.1.5.0-A2JAkaXM35zEGvz8eJSuVp/libsass.a
    The symbol was previously defined in
       /Users/tom/.stack/snapshots/x86_64-osx/lts-7.14/8.0.1/lib/x86_64-osx-ghc-8.0.1/hlibsass-0.1.5.0-A2JAkaXM35zEGvz8eJSuVp/libsass.a(ast.o)
    This could be caused by:
       * Loading two different object files which export the same symbol
       * Specifying the same object file twice on the GHCi command line
       * An incorrect `package.conf' entry, causing some object to be
         loaded twice.
    ghc: Could not on-demand load symbol '__ZN4Sass8Argument4hashEv'

    GHC runtime linker: fatal error: I found a duplicate definition for symbol
       __ZN4Sass8Argument4hashEv
    whilst processing object file
       /Users/tom/.stack/snapshots/x86_64-osx/lts-7.14/8.0.1/lib/x86_64-osx-ghc-8.0.1/hlibsass-0.1.5.0-A2JAkaXM35zEGvz8eJSuVp/libsass.a
    The symbol was previously defined in
       /Users/tom/.stack/snapshots/x86_64-osx/lts-7.14/8.0.1/lib/x86_64-osx-ghc-8.0.1/hlibsass-0.1.5.0-A2JAkaXM35zEGvz8eJSuVp/libsass.a(bind.o)
    This could be caused by:
       * Loading two different object files which export the same symbol
       * Specifying the same object file twice on the GHCi command line
       * An incorrect `package.conf' entry, causing some object to be
         loaded twice.
```

There are a couple more similar symbol errors below, but you get the idea. Thanks in advance for any help!

**Comment by jakubfijalkowski** [comment]
Hi!

Does this error occur in GHCi only? GHCi seems to have problems with loading correct `libstdc++` and this is "known bug" (see [hLibsass readme](https://github.com/jakubfijalkowski/hlibsass#static-shared-or-external-version-of-libsass) ). Moreover, check the issue jakubfijalkowski/hlibsass#6 - it seems to be the same (and related to shared libraries).

I will probably be able to check and try to fix this once and for all on the weekend. I'll come back in a few days.

**Comment by thomasjm** [comment]
Yeah, the error happened when using GHCi, but not when I ran `stack build` on `hsass` itself. Looks like it's the same as the issue you linked. Thanks!

**Comment by nrolland** [comment]
@thomasjm could you get it to work ? I just upgraded to Sierra and I have the same pb again....

**Comment by thomasjm** [comment]
Nope, still waiting on a fix.

**Comment by nrolland** [comment]
can you compile `hsass` with the flags 

```
flags:
  hlibsass:
    externalLibsass: true
``` 

in the `stack.yaml` ?

I get 

```
Progress: 1/2
--  While building package hlibsass-0.1.5.0 using:
      /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack91128/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 configure --with-ghc=/Users/nrolland/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --with-ghc-pkg=/Users/nrolland/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --with-ghcjs=/Users/nrolland/.local/bin/ghcjs --with-ghcjs-pkg=/Users/nrolland/.local/bin/ghcjs-pkg --user --package-db=clear --package-db=global --package-db=/Users/nrolland/.stack/snapshots/x86_64-osx/lts-8.5/8.0.2/pkgdb --package-db=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/pkgdb --libdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/lib --bindir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/bin --datadir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/share --libexecdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/libexec --sysconfdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/etc --docdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/doc/hlibsass-0.1.5.0 --htmldir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/doc/hlibsass-0.1.5.0 --haddockdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/doc/hlibsass-0.1.5.0 --dependency=base=base-4.9.1.0 -fexternalLibsass -f-sharedlibsass --exact-configuration
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/nrolland/Sync/clones/hsass/.stack-work/logs/hlibsass-0.1.5.0.log

    [1 of 2] Compiling Main             ( /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack91128/hlibsass-0.1.5.0/Setup.hs, /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack91128/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/nrolland/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack91128/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack91128/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup ...
    Configuring hlibsass-0.1.5.0...
    setup: Missing dependency on a foreign library:
    * Missing C library: sass
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

the program `sass` is on my path. not sure if it should be specified elsewhere for cabal (or some other voodoo) to know where it is.


Adding the location of `which sass` to `stack.yaml` does not change anything

```
extra-include-dirs:
- /Users/nrolland/.rvm/gems/ruby-2.3.3/bin/
extra-lib-dirs:
- /Users/nrolland/.rvm/gems/ruby-2.3.3/bin/
```

```

$ stack build                                                                                                                                                                                                                                                             not sandboxed
hlibsass-0.1.5.0: configure
Progress: 1/2
--  While building package hlibsass-0.1.5.0 using:
      /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack94353/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 configure --with-ghc=/Users/nrolland/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --with-ghc-pkg=/Users/nrolland/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --with-ghcjs=/Users/nrolland/.local/bin/ghcjs --with-ghcjs-pkg=/Users/nrolland/.local/bin/ghcjs-pkg --user --package-db=clear --package-db=global --package-db=/Users/nrolland/.stack/snapshots/x86_64-osx/lts-8.5/8.0.2/pkgdb --package-db=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/pkgdb --libdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/lib --bindir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/bin --datadir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/share --libexecdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/libexec --sysconfdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/etc --docdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/doc/hlibsass-0.1.5.0 --htmldir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/doc/hlibsass-0.1.5.0 --haddockdir=/Users/nrolland/Sync/clones/hsass/.stack-work/install/x86_64-osx/lts-8.5/8.0.2/doc/hlibsass-0.1.5.0 --dependency=base=base-4.9.1.0 -fexternalLibsass -f-sharedlibsass --extra-include-dirs=/Users/nrolland/.rvm/gems/ruby-2.3.3/bin --extra-lib-dirs=/Users/nrolland/.rvm/gems/ruby-2.3.3/bin --exact-configuration
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/nrolland/Sync/clones/hsass/.stack-work/logs/hlibsass-0.1.5.0.log

    [1 of 2] Compiling Main             ( /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack94353/hlibsass-0.1.5.0/Setup.hs, /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack94353/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/nrolland/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack94353/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /private/var/folders/9d/vgq7v77x27xb7v93gg85bcmc0000gn/T/stack94353/hlibsass-0.1.5.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup ...
    Configuring hlibsass-0.1.5.0...
    setup: Missing dependency on a foreign library:
    * Missing C library: sass
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

**Comment by jakubfijalkowski** [comment]
Okay, I have no idea what is going on. I think this problem is unrelated to the previous one (the GHCi not being able to load `hlibsass`) and occurs only on LTS-8. The fun thing is, [Travis](https://travis-ci.org/jakubfijalkowski/hsass) is able to build and test hsass under GHC 8.0.2 and stack 1.4. I have been unable to do so just a second ago (up-to-date Mint 18.1), but after some magic (nuking `.stack-work`, building under LTS-6, nuking, building under LTS-8 and some other steps that I don't remember), it just started to work. After `stack clean` it stopped, but I think it might be repeatable.

I need to dig deeper into the newest stack, GHC and Cabal. I don't know when I will be able to do so, but I hope it won't take me another year (I have finally started to have some time for things other than my studies and work, but I don't know if it stays like that for long). I made a promise to fix this a couple of times now, but I failed miserably (different priorities) - sorry for that.

**Comment by nrolland** [comment]
That would be nice of course. Are other packages relying on external libraries relying on the same specific setup.hs ? If it really is necessary to have an ad-hoc setup, having a nix option flag might be a way that to normalize the behavior across platforms (and delegating normalization), as you can abstract the location business by shelling out some nix commands

**Comment by jakubfijalkowski** [comment]
If I understand your question correctly - yes, other libs do rely on a custom `Setup.hs`, if one of the dependencies do have one. Because `libsass` wasn't available as a distro package (at least not in Ubuntu, but that was 2 years ago), I have chosen to use custom setup and compile and link with `libsass` manually. There are many issues with this approach, but I had (or haven't knew about) no other choice.

Unfortunately, I know nothing about nix, but I'll check it out.

**Comment by jakubfijalkowski** [comment]
Okay, the problem with compilation should be fixed in `hlibsass` 0.1.5.2 and `hsass` 0.4.1. Could you check, please?

Also, with GHC 8.0.2, `Cabal-1.24` and `stack 1.4` (i.e LTS Haskell 8.5), GHCi seems to work, even with statically (and locally-built) linked `libsass`. Can you confirm?

**Comment by nrolland** [comment]
I could compile on `stack 1.4` with `hlibsass`  0.1.5.2 both `hsass` and my project, provided I do not specify

```
flags:
  hlibsass:
    externalLibsass: true
```

ps : what's the best reference for what's going on in `Setup.hs` in your opinion ?

**Comment by jakubfijalkowski** [comment]
What happens when you set the `externalLibsass` flag to `true`? Do you have `libsass.a` on the search path? It works for me (Linux Mint 18.1 with LibSass 3.3.4 from Ubuntu Xenial repo), but I am currently unable to check on macOS.

Moreover - do GHCi work now?

Ad. PS - do you mean `Setup.hs` from `hlibsass` or generally custom setup scripts? If generally - I ended up reading `Cabal` code, doing printf-style debugging and just experimenting. I couldn't find any comprehensive documentation for this.

**Comment by nrolland** [comment]
External option works on this project `hsass` by adding to `stack.yaml`

```
extra-lib-dirs:   #this is passed to GHC
- /usr/local/lib  #where your libs are

flags:
  hlibsass:
    externalLibsass: true
```

I could compile once my other project but upon testing other ways to install libsass, I had the following error 

```
$ stack build                                                                                                                                                                              
xquant2-0.1.0.0: build (exe)
Log files have been written to: /Users/nrolland/Sync/clones/xquant2/.stack-work/logs/

--  While building package xquant2-0.1.0.0 using:
      /Users/nrolland/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build exe:xquant2 --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/nrolland/Sync/clones/xquant2/.stack-work/logs/xquant2-0.1.0.0.log

    Preprocessing executable 'xquant2' for xquant2-0.1.0.0...
    Linking .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/xquant2/xquant2 ...
    Undefined symbols for architecture x86_64:
      "_sass_option_get_plugin_path", referenced from:
          _chb9_info in libHShlibsass-0.1.5.2-1oW1V9GIDOwBgO0dG4ULhr.a(Context.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    `gcc' failed in phase `Linker'. (Exit code: 1)

```

Which I imagined comes from some mismatch between expected `libsass` version of  'hlibsass'.
Although I see `plugin_path` both in 'current' [libsass](https://github.com/sass/libsass/blob/master/docs/api-context.md) and in 'current' [hlibsass](https://hackage.haskell.org/package/hlibsass-0.1.5.2/docs/src/Bindings-Libsass-Context.html#sass_option_get_plugin_path)


It turned out it that installing via `brew install --HEAD libsass` caused the failure, while `brew install libsass` works fine.  Using `head` and pray is plain wrong. Nix is really great for that. Cross platform, it really pins down which version gets used. I guess that's a prime exemple for the nix facility in stack.

Thanks for having a look at that `Setup.hs`, this is typically out of reach for casual users.
Even for me, although I am not so unfamiliar with Haskell, I am in a phase where I dont use everyday right now and just wanted to use it casually... So thanks ;)

**Comment by jakubfijalkowski** [comment]
Big thanks for the check. I consider this issue closed. :)

Next - nix. Will look at it sometime soon. The probable version mismatch was the thing that I've wanted to avoid (the other being `libsass` not available as a precompiled package, but that was long ago), hence the custom setup. :) 

Yeah, `Setup.hs` is quite cryptic, but it's just scary and not that hard, really. I don't consider myself a "professional Haskeller" (I haven't used it for anything serious yet), but still been able to grasp it. Cabal people did a great job making the source code readable.

**Comment by dantiel** [comment]
impossible to link on High Siierra. anyway its still easily possible to use sass with the shell wrapper and just read from stdin `sass -s`.
