### ISSUE TITLE
Including encoding information in text is error-prone

### ISSUE THREAD

**Issue by h-3-0** [jakubfijalkowski/hsass#8]
When libsass outputs UTF-8 characters outside of the ASCII range, it prefixes its output with encoding information. Depending on the level of compression, this is either in the form of `@charset "UTF-8"` or a Byte-Order Mark. For the unwary (me), the BOM inclusion can cause problems.

As an example, naively concatenating CSS causes styling bugs:
```haskell
> let sass = "h1:before {\n    content: \"\9660\";\n}\n\n"
> let opts = def { sassOutputStyle = SassStyleCompressed }
> compileString sass opts >>= \(Right x) -> print @String (x ++ x)
"\65279h1:before{content:\"\9660\"}\n\65279h1:before{content:\"\9660\"}\n"
> --                                 ^ pesky BOM ends up in the middle of CSS
```

According to https://github.com/sass/sass/issues/1395 this is not configurable; it's the up to the CSS concatenater to handle this correctly. Fine. But we're using Haskell, we have expressive types, and I think we can be more user-friendly.

In my opinion, encoding information does not belong in text (e.g. in `String`, `Text`). Not only is the in-memory encoding an implementation detail, but the encoding only matters when converting to a `Bytestring`, or when performing IO. Having encoding information in-line is therefore error-prone and inconsistent (a BOM gets automatically converted -- obviously `@charset "UTF-8"` does not).

For backwards compatibility, I think it's better not to change any existing behaviour. But a new instance of `SassResult` could be added that's equivalent to `(Bool, String)`. This would strip encoding information from the `String` if needed, and indicate whether it had done so. Using this new feature would make CSS concatenation straightforward.

If this sounds sensible, I'm willing to implement it (or something similar, suggestions are welcome).

**Comment by jakubfijalkowski** [comment]
I'll look at it some more tomorrow evening (and will post my thoughts here) but your solution seems good and I would welcome the change.

**Comment by jakubfijalkowski** [comment]
I've looked at the problem and I agree with you - this needs to be solved.

Regarding your solution - do we really need the flag? I think that introducing `newtype` that's equivalent to `String`/`ByteString` with stripped BOM or `@charset "UTF-8"` would be a cleaner solution. Also, if the flag would be helpful, I would rather encode it in the types themselves (i.e. use `Either String StringWoBOM` or sth like that).

**Comment by h-3-0** [comment]
> do we really need the flag?

To flesh out my initial idea, consider:
```haskell
data EncodingStripped a = EncodingStripped Bool a

instance Monoid a => Monoid (EncodingStripped a) where
  EncodingStripped a b `mappend` EncodingStripped c d = EncodingStripped (a || c) (b <> d)
  mempty = EncodingStripped False mempty
```
Then a user concatenating the CSS from several Sass files can tell if the result is ASCII encodable without having to do redundant work. If they don't care, this has a slight advantage over 
```haskell
data EncodingStripped a = AsciiEncodable a | NotAsciiEncodable a
```
in that they only need to match against one pattern (`EncodingStripped _ t`) rather than two.

But now that I think about it, I'm not sure the `Monoid` instance would be useful. If you're concatenating CSS, you probably have only a single Sass file that everything is imported into, and so any other CSS is from a different source.

For *my* purpose, I need to unconditionally remove the encoding information. So I think I'll implement it the way you suggest — if a different interface is desired, it will be easy to adapt.

**Comment by jakubfijalkowski** [comment]
Ah, I completely have missed that the flag would indicate whether the string is ASCII or not (and that the BOM-stripping indicator is just a side effect). Still, I think that this wouldn't be that useful - you either don't care about encoding, BOMs etc. (and use the first version), or just use UTF-8 (because _something_ will eventually force you to it) and want the BOM stripped (and thus have the `Monoid` instance for free).
